export { default as HomePage } from "./HomePage"
export { default as Signup } from "./Signup"
export { default as Login } from "./Login"
export { default as Dashboard } from './Dashboard'
export { default as Savings } from './Savings'
export { default as Vault } from './Vault'
export { default as ReferralID } from './ReferralID'
export { default as Blog } from './Blog'
export { default as Calculator } from './Calculator'